name: JunkJam
title: JunkJam India
description: JunkJam is a global, multi-platform media and entertainment company.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: junkjam2015@gmail.com
disqus_username: junkjam
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Blog
    url: https://blog.junkjam.in
  - title: WhatsApp
    url: https://whatsapp.junkjam.in
  - title: Meme
    url: https://meme.junkjam.in
  - title: Feed
    url: /feed.xml